# Generated by Django 6.1.1 on 2026-09-27 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagegen', '0002_aiconfig_credit_cost_generatedimage_credit_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('verifier', models.CharField(help_text='Key into credits.challenges.VERIFIERS.', max_length=60)),
                ('reward_credits', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('max_rewards_per_user', models.PositiveIntegerField(default=1, help_text='0 means the challenge can be completed without limit.')),
            ],
            options={
                'ordering': ['reward_credits', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('generation', 'Generation charge'), ('reward', 'Reward'), ('refund', 'Refund'), ('adjustment', 'Admin adjustment')], max_length=20)),
                ('amount', models.IntegerField(help_text='Signed: positive credits in, negative credits out.')),
                ('balance_after', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='credits.challenge')),
                ('generation', models.ForeignKey(blank=True, help_text='The generation this movement belongs to, when there is one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='imagegen.generatedimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('evidence', models.CharField(blank=True, default='', help_text='The proof a verifier inspects (a user id, a post link, …).', max_length=500)),
                ('detail', models.CharField(blank=True, default='', help_text='Why a verification was rejected, when it was.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='credits.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_completions', to=settings.AUTH_USER_MODEL)),
                ('reward_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_completion', to='credits.credittransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['user', '-created_at'], name='credits_cre_user_id_6943f8_idx'),
        ),
        migrations.AddIndex(
            model_name='challengecompletion',
            index=models.Index(fields=['user', 'challenge', 'status'], name='credits_cha_user_id_43f7fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='challengecompletion',
            constraint=models.UniqueConstraint(fields=('challenge', 'user', 'evidence'), name='unique_challenge_evidence_per_user'),
        ),
    ]
