# Generated by Django 6.1.1 on 2026-10-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_audio_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, help_text='Intrinsic height of `image` in pixels, captured on save.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_webp',
            field=models.ImageField(blank=True, help_text='WebP derivative of `image`, generated automatically.', null=True, upload_to='posts/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, help_text='Intrinsic width of `image` in pixels, captured on save.', null=True),
        ),
    ]
