# Generated by Django 6.1.1 on 2026-10-02

from django.db import migrations, models
from django.utils.text import slugify


SLUG_MAX_LENGTH = 220


def populate_post_slugs(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    db_alias = schema_editor.connection.alias

    for post in Post.objects.using(db_alias).order_by("pk").iterator():
        base = slugify(post.title, allow_unicode=True)
        if not base:
            base = slugify((post.prompt or "")[:120], allow_unicode=True)
        if not base:
            base = "post"
        if base.isdigit():
            base = f"post-{base}"
        base = base[:SLUG_MAX_LENGTH]

        candidate = base
        suffix = 2
        while Post.objects.using(db_alias).filter(slug=candidate).exclude(pk=post.pk).exists():
            suffix_text = f"-{suffix}"
            candidate = f"{base[:SLUG_MAX_LENGTH - len(suffix_text)]}{suffix_text}"
            suffix += 1

        post.slug = candidate
        post.save(using=db_alias, update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_image_height_post_image_webp_post_image_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                editable=False,
                max_length=SLUG_MAX_LENGTH,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(populate_post_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                editable=False,
                max_length=SLUG_MAX_LENGTH,
                unique=True,
            ),
        ),
    ]
