# Generated by Django 6.1.1 on 2026-09-27 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_follow_unique_follow_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit_balance',
            field=models.PositiveIntegerField(default=0, help_text='Credits available for AI generations. Managed by credits.services.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
