# Generated by Django 6.1.1 on 2026-09-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagegen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='credit_cost',
            field=models.PositiveIntegerField(default=80, help_text='Credits charged per generation. Configurable per model/provider by editing this row.'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='credit_cost',
            field=models.PositiveIntegerField(default=0, help_text='Credits charged for this generation, for refunds and audits.'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='source_image',
            field=models.ImageField(blank=True, help_text='The reference image this generation was remixed from (image-to-image).', null=True, upload_to='generated_sources/%Y/%m/'),
        ),
    ]
